### ISSUE TITLE
Deactivated user on Console is able to login to the suspending company on Twake Web

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1765] opened 2021-11-24 09:50 UTC
# Precondition
- The user is deactivated on My Company
![image](https://user-images.githubusercontent.com/69950655/143211685-85804100-c571-489b-82b5-56eef49f5642.png)

# Actual Result
The deactivated user is still able to login to the company that he is suspended.
![image](https://user-images.githubusercontent.com/69950655/143213842-fd8a991e-a06b-4937-b443-5b9feddae950.png)

# Expected Result
The deactivated user shouldn't be able to login to the company he is suspended
Refer to the story from Console side: https://ci.linagora.com/linagora/lgs/saas/portal/specifications/-/issues/30

# Environment
QA environment
Chrome on Ubuntu

**Comment by RomaricMourgues** [comment] 2021-11-24 09:52
Duplicate of #1001 and #1257

**Closed** 2021-11-24 10:29 UTC
Labels: bug, Major
