### ISSUE TITLE
Verify email modal on every login

### ISSUE THREAD

**Issue by tennox** [linagora/Twake#1090] opened 2021-03-30 22:57 UTC
**Describe the bug**
The email confirmation dialogue is shown everytime I log in even though I did confirm. 
It then also shows "user already confirmed" when I click resend. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2084639/113199553-8b393100-9267-11eb-839b-1f4bb118be72.png)

**Desktop firefox** did the same 
**Smartphone (please complete the following information):**
 - Device: OnePlus6T
 - OS: Android 10
 - Browser Firefox
 - Version?

**Comment by RomaricMourgues** [comment] 2021-04-01 07:59
Hi, thanks for the feedback, this is a duplicate of #1054 , we're working on it :)

**Closed** 2021-06-30 13:47 UTC
