### ISSUE TITLE
[Bug] User picker not working for channel

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake#1873] opened 2022-01-05 10:50 UTC
**Describe the bug**
When I try to add user in a channel, sometime, the backend result are not shown

**To Reproduce**
1. Got to Twake software
2. Try to add "Nguyen huy"
3. Nothing is shown, but backend send 2 results

**Screenshots**

https://user-images.githubusercontent.com/22451567/148205771-a03dadc4-3fe7-4f96-8bd3-8afb5252a183.mov

**Desktop (please complete the following information):**

**Comment by hantt12** [comment] 2022-02-22 09:20
Did you update this to QA Platform?

**Comment by RomaricMourgues** [comment] 2022-02-22 11:41
This issue is unclear (preview shows Tasks but talk about channels) and a duplicate of other in progress issues (#1960, #1975, #1821, #1219, #1719) so I'll close it for now

**Closed by RomaricMourgues** 2022-02-22 11:41 UTC
Labels: bug, Medium, Twake Tasks
