### ISSUE TITLE
Unable to add Guest to channel

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1829] opened 2021-12-16 03:10 UTC
1. Go to a channel
2. Select Guest Management
3. Add a guest

Expected result:
Invitation email is sent to Guest

Actual result:
Error message is shown
Email is not sent

![2021-12-16_10-08-25.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/1d2ae404-fa9d-40e1-b7dd-51cc626ff925)

**Comment by RomaricMourgues** [comment] 2021-12-16 10:27
It worked on my new company, ![Screenshot 2021-12-16 at 11.26.43.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/2628fb1e-87de-4b82-b535-a896ae34ce62)![Screenshot 2021-12-16 at 11.26.48.png](https://images.zenhubusercontent.com/5f06c9fd1b73b723f6b6bf16/b5b00f77-9efd-4eee-a470-16d265cd0e8c)

Could you give me the API reply ?

**Comment by RomaricMourgues** [comment] 2022-02-15 08:39
Duplicate of #1921

**Closed by RomaricMourgues** 2022-02-15 08:39 UTC
Labels: bug, Major
