### ISSUE TITLE
[Add member] Don't display member in list user in twake console after add member in twake web

### ISSUE THREAD

**Issue by hieuhoang998** [linagora/Twake#1258] opened 2021-05-07 08:02 UTC
## Describe the bug

Don't display member in list user in twake console after add member in twake web

### Precondition: Owner just sign up successfully

- 1.Click add member in pop up

- 2.Input email (member has already exist)

- 3.Click Start using twake button

### Server
 - staging
### Client 
- Desktop (please complete the following information):*

  - Firefox ,version 85.0.2

  - Chrome version 88.0.4

- Mobie Oppo reno version 11.1,chrome app

**Comment by hieuhoang998** [comment] 2021-05-27 06:43
I can't check cause when sign up then system redirect to sign in page in stead of twake web.

**Comment by BenoitTallandier** [comment] 2022-01-18 10:03
It's not a bug anymore. I close the issue.
https://images.zenhubusercontent.com/271994210/a3aa9cda-ec8c-4dcc-afa0-ba5619faeb48/membersadd.mov

**Closed by BenoitTallandier** 2022-01-18 10:03 UTC
Labels: bug, Major
