### ISSUE TITLE
PNG support for avatar

### ISSUE THREAD

**Issue by digitalfredy** [linagora/Twake#436] opened 2020-10-20 14:14 UTC
**Describe the bug**
PNG is not supported for avatar and user does not get error message when try to upload png files.

**To Reproduce**
1. Go to Account Settings
2. Click on Identity
3. Click on the avatar square
4. Try to load a png avatar (less that 5MB)

**Expected behavior**
Take supposed to upload, set and show the avatar in png format
Worst case show an error message to inform that png format is not supported
Right now nothing happen and is not clear what's going on.

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser Chrome, Firefox

**Comment by RomaricMourgues** [comment] 2021-08-03 12:46
@stephanevieira75 maybe already fixed with Console

**Comment by stephanevieira75** [comment] 2021-08-06 12:45
@RomaricMourgues i tried to reproduce and looks like it's working now

Should i close this issue ?

**Comment by RomaricMourgues** [comment] 2021-08-06 13:31
Did you try with transparent background ?

**Comment by RomaricMourgues** [comment] 2021-08-30 08:37
It's good

**Closed by RomaricMourgues** 2021-08-30 08:37 UTC
Labels: bug
